name: CI for Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change directory to server and install dependencies
        run: |
          cd server
          npm install

      - name: Run backend tests
        run: |
          cd server
          npm test
        env:
          GCLOUD_STORAGE_BUCKET: ${{ secrets.GCLOUD_STORAGE_BUCKET }}
          LOCAL_MONGODB_URI: ${{ secrets.LOCAL_MONGODB_URI }}

  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change directory to webclient and install dependencies
        run: |
          cd webclient
          npm install

      - name: Run frontend tests
        run: |
          cd webclient
          npm test
